Test: 플랜 컨트롤러 테스트 코드 추가
New-Barams/This-Year-Ajaja-BE pull request #154
Opened 2024-01-20 18:52 UTC by kys0411

# 🔍 어떤 PR인가요?
- 플랜 컨트롤러 테스트 코드를 추가하였습니다.

# ✅ 작성한 테스트
- [x] deletePlan_Success
- [x] createPlan_Success
- [x] getPlan_Success
- [x] updatePlanPublicStatus_Success
- [x] updatePlanRemindStatus_Success
- [x] updatePlanAjajaStatus_Success

 

[//]: # (# 🫡 관련 Issue )

2024-01-21 13:49 UTC, Hejow reviewed
예외 상황만 반영되면 바로 merge하고 swagger 걷어내시죠!

2024-01-23 08:50 UTC, Hejow requested changes

2024-01-23 08:50 UTC, Hejow commented on src/test/java/com/newbarams/ajaja/module/plan/presentation/PlanControllerTest.java
> +	@DisplayName("토큰 검증에 실패할 경우 400 에러를 반환한다.")
이거 복붙하시니까.. 뭐가 뭔지 모르겠어요 API 명이라도 적어주세요 ㅠㅠ

2024-01-23 08:50 UTC, Hejow commented on src/test/java/com/newbarams/ajaja/module/plan/presentation/PlanControllerTest.java
> +	void updatePlan_Fail_By_Not_Found_Plan() throws Exception {
이런식으로 컨벤션을 하지 않았던 것 같아요! 다른 테스트도 변경하면 좋을 것 같아요!
to-be : `updatePlan_Fail_ByNotFoundPlan`

2024-01-23 09:25 UTC, kys0411 commented on src/test/java/com/newbarams/ajaja/module/plan/presentation/PlanControllerTest.java
> +	void updatePlan_Fail_By_Not_Found_Plan() throws Exception {
헉 어쩐지.. 수정해씁니다~!

2024-01-23 09:26 UTC, kys0411 commented on src/test/java/com/newbarams/ajaja/module/plan/presentation/PlanControllerTest.java
> +	@DisplayName("토큰 검증에 실패할 경우 400 에러를 반환한다.")
수정했습니다~!

2024-01-23 17:20 UTC, Hejow approved these changes
작성하시느라 고생하셨어요!

2024-01-23 17:25 UTC, merged