Add(.footprint) : 발자취 도메인 객체 추가
New-Barams/This-Year-Ajaja-BE pull request #177
Opened 2024-02-12 07:28 UTC by JuwoongKim

# 🔍 어떤 PR인가요?
- 발자취 도메인 객체를 설계했습니다.

- 도메인 규칙까진 구현하지 않고 필요한 객체와 관계만 표현했습니다.
- 혼자만의 고민이 길어지는 것 같아 PR 단위를 짧게 해서 소통해야할 필요성을 느꼈습니다.
- 논의가 이뤄진 후 하나의 도메인 규칙을  PR 단위로 해서 작성하려 합니다.

# 😋 To Reviewer
- 다양한 형식의 회고를 추상 클래스에서 상속받는 방식으로 구현했습니다. 

- 추상 클래스 제약으로 인해 정적 메서드를 사용해서 생성하는 방식을 보류하고 생성자를 사용하고 있습니다.
- 생성자에 파라미터가 많아 별도의 파라미터 DTO를 만들고 사용자 정의 생성자를 만들었습니다.
   다만 fixture-monkey의 장점을 통해 테스트 코드를 작성하려다보니 다소 dto에 새로운 생성자를 추가하는 어색함이 있습니다.
- Monkey support의 fixture monkey 사용 시 이상하게 생성자를 통한 방식이 적용되지 않았습니다. 테스트 및 조사 결과 
   FailoverIntrospector를 삭제하고 ConstructorPropertiesArbitraryIntrospector 만 적용했을 시 됩니다. 
   저는 필드값이 많아  반드시 Fixture Monkey를 사용하고 싶었고 공통 설정을 변경할 수 없어 테스트 코드의 멤버변수로  Fixture Monkey를 하 나 더 추가 했습니다.

# ✅ 작성한 테스트
- [ ] createFreeFootprint_Success_WithNoException
- [ ] createKPTFootprint_Success_WithNoException

 

[//]: # (# 🫡 관련 Issue )

2024-02-12 12:15 UTC, kys0411 reviewed
주웅님 첫 PR 고생많으셨습니다ㅎㅎ!

2024-02-12 12:15 UTC, kys0411 commented on src/main/java/me/ajaja/module/footprint/domain/Ajaja.java
> +	private final String nickName;
닉네임은 어떤 이유때문에 들어가나용?.?

2024-02-12 12:15 UTC, kys0411 commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +	}
파라미터 네이밍 그냥 param으로 해도 충분할 것 같긴 합니다! 그냥 제 의견이에용ㅎ

2024-02-12 12:15 UTC, kys0411 commented on src/main/java/me/ajaja/module/footprint/domain/TargetPlan.java
> +	private final Long targetPlanId;
그냥 Target으로 네이밍해도 의미전달이 될 것 같아요ㅎㅎ 제생각입니닷

2024-02-12 12:15 UTC, kys0411 commented on src/main/java/me/ajaja/module/footprint/dto/FootprintParam.java
> +			FootprintStatus footprintStatus, Set<Tag> tags, List<Ajaja> ajajas
foot print create할 때 아좌좌가 들어오는 경우가 있나요?.?

2024-02-12 12:15 UTC, kys0411 commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +		.build();
monkeysupport를 상속받을 이유가 없는 것 같아용!

2024-02-12 12:29 UTC, JuwoongKim commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +		.build();
요게 제가  SupportMonkey에 있는 sut를 사용하면 생성자로 객체 생성이 안되더라고요.
설정대로라면 되야하는데.. 

PR에도 언급헀는데 무슨 차인지 알기 힘들어서 한번 올려봤습니다.
테스트해본결과 SupportMonkey에 있는 sut도 해당 파일처럼 설정하면 생성자로 객체 생성이 되더라고요 
우선 다른 분들 의견을 좀 더 들어볼게요. 

말씀하신것 처럼 상속할 필요가 없긴한데, 컨벤션 같은 느낌이라 좀 애매하네요

2024-02-12 12:34 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/dto/FootprintParam.java
> +			FootprintStatus footprintStatus, Set<Tag> tags, List<Ajaja> ajajas
없습니다.
사실 불필요하다고 생각하는데 tags 초기화하는거랑 일관성있게 하려고 우선 저렇게 표현해봤습니다.
지금 보니깐 지우는게 맞다고 생각해서 수정해보도록 하겠습니다.

별도로 DTO에 테스트 코드 작성을 위해 저렇게 생성자를 따로 만드는건 어떻게 생각하세요? 
애너테이션만 사용하면서 @ConstructorProperties 를 적용하고 싶은데 좀 힘들더라고요 ㅠㅠ

2024-02-12 12:38 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/TargetPlan.java
> +	private final Long targetPlanId;
네!! 리마인드를 고려하면 일관성있게 Target으로 변경하는게 좋아보입니다.

2024-02-12 12:39 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +	}
더 깔끔한 것 같습니다!!

2024-02-12 12:43 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Ajaja.java
> +	private final String nickName;
실제로 화면 조회에 사용한다면 ID 값보다는 사용자 이름이 더 필요하다고 생각했습니다!
근데 지금 Ajaja보니깐 애초에 사용자 이름이 없네유!!
당시에 아좌좌선택한 사용자 정보도 나중에 필요하지 않을까 생각했는데 불필요한 고민이였던 것 같아요!!
삭제도록 하겠습니다.

2024-02-12 13:54 UTC, 2jie0516 reviewed
첫 pr 수고하셨습니다 🥳

2024-02-12 13:54 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/footprint/domain/Ajaja.java
> +public class Ajaja extends SelfValidating<Ajaja> {
기존에 이미 있는 ajaja 도메인을 안쓰시고 새로 설계하신 이유가 있나요 ??

2024-02-12 13:54 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +	private final TargetPlan targetPlan;
예슬님 말대로 그냥 Target으로 해도 충분할 것 같습니다 ! ㅎㅎ

2024-02-12 13:54 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/footprint/domain/FootprintStatus.java
> +	void switchPublic() {
상태를 바꾼다라는 것을 표현하고 싶으셨던 거면 그냥 switch 라는 네이밍도 괜찮을 것 같습니다!

2024-02-12 13:54 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/footprint/domain/FootprintStatus.java
> +	void toDeleted() {
toDeleted는 내부 구현을 굳이 드러내는 것 같아서 그냥 delete()로 해도 괜찮을 것 같다는 개인적인 의견입니다..!

2024-02-12 13:54 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/footprint/domain/FreeFootprint.java
> +	private Blob content;
혹시 blob 사용하신 이유 알 수 있을까용??

2024-02-12 14:31 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/FreeFootprint.java
> +	private Blob content;
잘못된 기억으로 String 객체는 길이 수 제한이 있고 Blob 이 이를 해결할 수 있다고 생각했습니다.
알아보니 String으로도 충분할 것 같습니다. 
애초에 제약이 없고 힙메모리 크기에 따라 달라진다고 하네요. 운영체제마다 다르고요. 
수정하도록 하겠습니다

2024-02-12 14:43 UTC, Hejow requested changes
작성하시느라 고생 많으셨어요!
여러가지 새로운 기술들이 많아서 학습하시느라 애 먹으셨을 것 같습니다 ㅎㅎ
남겨드린 리뷰 확인해보시면 좋을 것 같습니다!

2024-02-12 14:43 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/Ajaja.java
> +	private final String nickName;
nickname은 합성어가 아닙니다 ㅋㅋ
근데 밑에 리뷰하다 보니까 다른 곳에는 잘 써놓으셧군요?

```suggestion
	@NotBlank
	@Size(max = 20)
	private final String nickname;
```

2024-02-12 14:43 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/Ajaja.java
> +	private final Long userId;
`writer.id` vs `writer.userId`

2024-02-12 14:43 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +		this.ajajas = (ajajas == null) ? new ArrayList<>() : footprintParam.getAjajas();
필드에서 기본값을 생성해주면되서 없어도 될 것 같습니다!

2024-02-12 14:43 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/FootprintStatus.java
> +	private boolean isPublic;
아 저희 컨벤션 상으로 boolean에 is를 붙이지 않습니다 ㅎㅎ!
참고하셔용~

2024-02-12 14:43 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/FootprintStatus.java
> +	void switchPublic() {
저는 개인적으로 그대로 유지하는게 낫다고 봅니당 ㅋㅋㅎ

2024-02-12 14:43 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +	public Footprint(FootprintParam.Create footprintParam) {
단 하나의 생성자에서 특정한 DTO를 받는 것은 조금 많은 제약을 주는 것 같습니다! (ex. 테스트 어려움)
우리는 롬복을 사용하고 있으니까 최대한 활용해보는 것은 어떨까요?

저는 개인적으로 builder를 자주 애용하지 않지만,
이렇게 (value를 통해서 충분히 줄였음에도 불구하고) 엔티티가 커져버린다면 (필드가 많아진다면) builder를 통해서 휴면 에러를 줄일 수 있을 것 같습니다.

따라서 `@AllArgsConstructor`와 `@Builder`를 사용해서 보일러 템플릿 코드를 줄이고,
Param DTO를 받는 객체는 정적 팩토리 메서드를 제공해서 테스트 용이성도 챙겨가는 확장을 고려해보시는 것은 어떤가요? 

아마 부모 객체가 존재하기 때문에 `@SuperBuilder`를 사용하셔야할 것 같습니다 ㅎㅎ

2024-02-12 14:43 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/Tag.java
> +	private final Long tagId;
`tag.id` vs `tag.tagId` 어떤게 더 나으신가요?
저는 개인적으로 변수명과 필드명을 구분하려고 하는데 이런 것도 고려해보시면 좋을 것 같습니다!

변수은 특정 스코프(메서드 바디)에서 임시로 할당되는 공간을 의미하기 때문에 직관적으로 userId, tagId라고 짓는게 좋다고 생각합니다.

반면에, 필드의 스코프는 클래스 내부로 클래스를 표현한다고 생각합니다.
따라서 네이밍도 이런 부분을 고려해서 지으면 좋을 것 같더라구요! ㅎㅎ

2024-02-12 14:43 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/Tag.java
> +	private final String tagName;
마찬가지입니당 ㅎㅎ

2024-02-12 14:43 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +public abstract class Footprint {
여기에 `SelfValidating`이 적용되지 않아서 자식 객체에서도 스스로 검증할 수 없겠군요~?!

2024-02-12 14:43 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/dto/FootprintParam.java
> +	public static class Create {
모든 value를 들고 있어서 실질적으로 어떻게 사용될지 모르겠습니다!
DTO를 적용하고 사용하는 순간은 나머지 layer를 구현하면서 고려해보셨으면 좋겠습니다 ㅎㅎ

2024-02-12 14:43 UTC, Hejow commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +		.build();
어떤 객체가 생성이 안되고 어떤 문제가 있는지 알려주시면 좋을 것 같아요!

2024-02-12 14:43 UTC, Hejow commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +				}
안티 패턴처럼 사용하고 계신 것 같습니다!!

try-catch로 예를 들면, try로 감싸지는 영역은 최소화가 되어야 원하는 부분만 catch해서 처리할 수 있습니다.
근데 지금 코드는 예외를 발생하는 부분이 너무 다양해서(넓어서) 생성에 대해서만 테스트하지 못하고 있는 것 같습니다!

2024-02-12 14:43 UTC, Hejow commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +
나중에 blob을 안 쓰시겠지만 이런식으로도 사용할 수 있습니다 ㅎㅎ
```suggestion
					var blobBuilder = sut.giveMeBuilder(Blob.class);
					Blob keepContent = blobBuilder.sample();
					Blob problemContent = blobBuilder.sample();
					Blob tryContent = blobBuilder.sample();
```

2024-02-12 14:44 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Ajaja.java
> +public class Ajaja extends SelfValidating<Ajaja> {
저는 모듈로 나눠진 이상 모듈간의 도메인 객체끼리 직접적인 참조는 없어야 한다고 생각했습니다.
따라서 ajajaId를 통해 연관관계를 표현하려 했습니다.
다만 해당 값도 유효성 검사가 필요하다고 싶어서 벨류 객체로 빼두었습니다.
이름만 동일할 뿐 모듈마다 다른 것이라고 생각했습니다.

또한 JPA 엔티티 도메인 엔티티와 동일하게 동일한 명이라도 모듈별로 각각 필요하다고 생각했어요
모듈마다 각자 다른 디비를 가질 수도 있으니깐요. 
대신 id값을 주고 받아서 모듈별로 요청할 수 있고요.

근데이부분은 팀원 모두가 논의를 해야할 것 같습니다.
@kys0411 @Hejow

2024-02-12 14:49 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/FootprintStatus.java
> +	void toDeleted() {
이게 상태변경이라 좀 고민이 되었던 것 같습니다. 예슬님과 일치하기도 하고요

조금더 고민해보겠습니다. delete가 좀더 직관적이긴하네요

2024-02-12 14:51 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Ajaja.java
> +	private final Long userId;
writer.id 라고 생각합니다!! 
옆에 두고 비교하니깐 확실히 다르네요.
막연하게 userId 라는 걸 표현하고 싶었나봐요,

2024-02-12 14:54 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +		this.ajajas = (ajajas == null) ? new ArrayList<>() : footprintParam.getAjajas();
생성 요청 시 태그가 있는 경우와 없는 경우를 생각하다보니 그랬었습니다.
말씀하신대로 필드에서 생성하고 태그를 addAll()로 받는 방식으로 하면 될 것 같습니다.
예슬님이 언급하신 ajaja 문제도 같이 해결할 수 있을 것 같습니다!

2024-02-12 15:10 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +	public Footprint(FootprintParam.Create footprintParam) {
좋습니다. 저도 매개변수를 줄이는 방법에 대해 조사하다가 객체로 한번에 받기를 선택했었습니다.
다만 이게 생성자로 받다보니 말씀하긴 대로 여러 제약이 발생했습니다. 
롬북을 사용해서 직관적으로 볼 수 있겠습니다.(그때 그 단어가 생각이 안나요.. 미간??)

정적팩토리 메서드를 조금 봐야겠지만 해당 클래스에서 DTO를 받고 내부에서 빌더를 통해 객체를 생성해보도록 하겠습니다.

2024-02-12 15:13 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +public abstract class Footprint {
그러네요... 추상클래스에 상속받도록해야겠습니다.

그러면 안타깝게도 자식 클래스들은 롬북 생성자를 사용하긴 힘들 겠네요...
탬플릿 항목을 따로빼는 건 어떻게 생각하세요??? 갠적으로 투머치라고 생각하는데 생각이 궁금해서 
@kys0411 @Hejow @2jie0516

2024-02-12 15:14 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/dto/FootprintParam.java
> +	public static class Create {
고려하도록 하겠습니다.
막연히 매개변수를 객체로 줄이겠다 라고만 생각했습니다!!

2024-02-12 15:19 UTC, JuwoongKim commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +				}
말씀하신 내용이 맞는 것 같습니다. 

다만 이게 예외가 발생하지 않는 성공 테스트라는점에서는 어떻게 생각하시나요??
의견이 궁금합니다.

우선은 생성 테스트라는 점에서 파라미터 생성부분을 따로 빼두고 생성 부분만 검증을 할 것 같습니다.
예를 들어 파라미터 부분을  beforeEach 같은 것으로 미리 빼둘 것 같기도 하고요

2024-02-12 15:20 UTC, JuwoongKim commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +
빌더가 있었군요!!! 픽스처 몽키랑 더 친해져야겠네요!!

2024-02-12 15:25 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Tag.java
> +	private final Long tagId;
동의보감입니다!

2024-02-12 15:35 UTC, JuwoongKim commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +		.build();
MonkeySupport 에서 생성한  sut 변수명의 FixtureMonkey를 사용한다면 

footprint 모듈 기준 Tag, Writer 같은 도메인 벨류, 그 밸류의 멤버가 final 이여서 생성자를 통해 Introspect 를 해야할 때 
다음과 같은 에러가 나옵니다. 
<img width="1345" alt="스크린샷 2024-02-13 오전 12 32 07" src="https://github.com/New-Barams/This-Year-Ajaja-BE/assets/62009283/7a12452a-c919-4ae3-a823-e920ea658597">

물론 공식문서에도 동일하게 예제 코드로 나와있긴하지만 전  FailoverIntrospector 방식이 뭔가 꼬인거라고 봐요.
<img width="691" alt="스크린샷 2024-02-13 오전 12 33 02" src="https://github.com/New-Barams/This-Year-Ajaja-BE/assets/62009283/a7dbd905-541b-487c-bcfe-33818ccfacb7">

이것만 삭제하고 ConstructorPropertiesArbitraryIntrospector 만 삭제하고 
.objectIntrospector(ConstructorPropertiesArbitraryIntrospector.INSTANCE) 사용하면 또 sut를 사용해도 생성자 방식으로 정상 동작합니다.

2024-02-12 15:47 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Ajaja.java
> +	private final String nickName;
완

2024-02-12 15:49 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/TargetPlan.java
> +	private final Long targetPlanId;
완

2024-02-12 15:50 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +	private final TargetPlan targetPlan;
완

2024-02-12 15:51 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/FootprintStatus.java
> +	void switchPublic() {
근데 두분다 근거가 뭐에유??

2024-02-12 15:58 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/FootprintStatus.java
> +	void toDeleted() {
완

2024-02-12 16:01 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/FreeFootprint.java
> +	private Blob content;
완

2024-02-12 16:01 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Ajaja.java
> +	private final Long userId;
완

2024-02-12 16:02 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/FootprintStatus.java
> +	private boolean isPublic;
완

2024-02-12 16:17 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/FootprintStatus.java
> +	void switchPublic() {
피드백 반영 :  f14fe9da4f1f2dce4ae3f0858e1b3676a1a8eb7b

isPublic 을 visible로 변경했습니다!
메서드 명은 switchVisibility로 변경했습니다!

2024-02-12 16:19 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Tag.java
> +	private final Long tagId;
피드백 반영 :  f14fe9da4f1f2dce4ae3f0858e1b3676a1a8eb7b

tagId 을 id로 변경했습니다!

2024-02-12 16:20 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Tag.java
> +	private final String tagName;
피드백 반영 :  f14fe9da4f1f2dce4ae3f0858e1b3676a1a8eb7b

tagName 을 name 으로 변경했습니다!

2024-02-12 16:27 UTC, Hejow commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +		.build();
`FailoverIntrospector` 이게 문제면 제조사 문의해야겠군요 ㅋㅋ

2024-02-12 16:27 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/Ajaja.java
> +public class Ajaja extends SelfValidating<Ajaja> {
모듈로 나뉘었다고 직접적인 참조가 없어야하는건 아니에요!

2024-02-12 16:28 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/FootprintStatus.java
> +	void switchPublic() {
switch만 있으면 무엇을 바꾸는지 모르기 때문입니당

2024-02-12 16:28 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/FootprintStatus.java
> +	void toDeleted() {
> 이게 상태변경이라 좀 고민이 되었던 것 같습니다. 예슬님과 일치하기도 하고요
> 
> 조금더 고민해보겠습니다. delete가 좀더 직관적이긴하네요

예슬님도 제가 수정 권고는 드렸었습니다 호호

2024-02-12 16:30 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +	public Footprint(FootprintParam.Create footprintParam) {
생성자에서는 빌더를 못 쓰니 정적 팩토리는 선택이 아니라 자연스럽게 필수가 될 것 같아요 ㅎㅎ

2024-02-12 16:31 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +public abstract class Footprint {
되지않을까요 ㅎㅎ?

2024-02-12 16:32 UTC, Hejow commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +				}
> 말씀하신 내용이 맞는 것 같습니다.
> 
> 다만 이게 예외가 발생하지 않는 성공 테스트라는점에서는 어떻게 생각하시나요?? 의견이 궁금합니다.
> 
> 우선은 생성 테스트라는 점에서 파라미터 생성부분을 따로 빼두고 생성 부분만 검증을 할 것 같습니다. 예를 들어 파라미터 부분을 beforeEach 같은 것으로 미리 빼둘 것 같기도 하고요

지금은 예외가 발생하지 않으나 라이브러리 스펙이 바뀌어서 나중에 예외가 발생하면 바로 실패하는 테스트가 되겠네요 ㅋㅋ!
생성 테스트면 생성만 테스트해야합니다. 
그리고 생성도 사실 어떤 설계적인 부분을 테스트했는지 드러내야할 것 같아요

2024-02-12 16:41 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +	public Footprint(FootprintParam.Create footprintParam) {
핵심은 파라미터 줄이기도 있지만 생성자에 대해서 이해하는 것도 중요합니당

2024-02-12 22:29 UTC, JuwoongKim commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +				}
네 알겠습니다!
혹시 설계적인 부분이라는 점을 좀 더 구체적으로 들어볼 수 있을까요?? 🥲🥲
메서드 같은 기능적인 측면일까요?? 
예를들면  단순 생성자보다는 생성하다 라는 메서드 테스트 같은!!

2024-02-12 22:43 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Ajaja.java
> +public class Ajaja extends SelfValidating<Ajaja> {
생각해보니 개인적인 기준이였던 것 같습니다.
tag 도메인 논의에서 각 도메인 별도의 중간 테이블을 사용했다는 점, 계획과 발자취에서 사용하는 아좌좌의 역할이 다르다는 점에서 분리에 좀 더 확신을 가졌던 것 같네요. 

팀원들과 함께 논의해보고 싶습니다.
제 방식을 유지하겠다는 의미가 아니고 지금 사용하는 방식을 사용하는 것도 좋을 것 같습니다.
다만 같이 고민해보는 것도 가치 있을 것 같다는 생각이 들었습니다.

2024-02-13 01:32 UTC, Hejow commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +				}
작성하려고 보니까 너무 길어서 구두로 설명드릴게요!

2024-02-13 08:37 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/domain/Ajaja.java
> +public class Ajaja extends SelfValidating<Ajaja> {
우선 주웅님 의견대로 진행하고 추후에 기능 들어오면서 수정해보도록 하겠습니다

2024-02-13 08:38 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/dto/FootprintParam.java
> +	public static class Create {
우선 내버려두고 기능 반영하면서 자세하게 보겠습니당 ㅎㅎ

2024-02-13 08:56 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/dto/FootprintParam.java
> +			FootprintStatus footprintStatus, Set<Tag> tags, List<Ajaja> ajajas
피드백 반영 : 6d25af2ad782078a868e72a79ee76be03cd79614

param 객체에서 아좌좌를 제거했습니다.

2024-02-13 09:00 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +	public Footprint(FootprintParam.Create footprintParam) {
피드백 반영 : 피드백 반영 : 6d25af2ad782078a868e72a79ee76be03cd79614

발자취 객체 내부에 정적 팩토리 메서드를 사용하고 빌더를 사용해봤는데 @SuperBuilder 의 접근 제한자 미지원으로 빌더가 노출되는 문제가 있었습니다. 또한 selfvalidation에도 제약이있었습니다.

팩토리 클래스를 따로 생성하고 생성 책임을 할당하고 발자취 객체는 생성자만 가져가도록 했습니다.

2024-02-13 09:01 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/domain/Footprint.java
> +public abstract class Footprint {
피드백 반영 : 피드백 반영 : 6d25af2ad782078a868e72a79ee76be03cd79614

반영했습니다.

2024-02-13 09:02 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/dto/FootprintParam.java
> +	public static class Create {
피드백 반영 : 피드백 반영 : 6d25af2ad782078a868e72a79ee76be03cd79614

우선 공통적인 부분만 받는 방식으로 변경했습니다.

2024-02-13 09:03 UTC, JuwoongKim commented on src/test/java/me/ajaja/module/footprint/domain/FootprintTest.java
> +				}
피드백 반영 : 7d9f1c11c3227a7c40e4d7ef253eb194253dcbb6

구두로 논의된 사항을 인지하고 테스트 코드를 수정했습니다.
다만 도메인 규칙에 대한 정의가 부족해서 기능 구현과함께 점진적으로 추가하도록 하겠습니다!

2024-02-13 09:07 UTC, JuwoongKim commented
별도의 팩토리 클래스를 만들어 발자취 도메인 생성에 대한 책임을 할당했습니다.
이유는 추상 클래스를 상속하는 상황에서 정적팩토리 메서드와 빌더 조합을 고려해봤지만 superBuilder의 접근제한자 한계,  SelfValidating 적용의 어려움때문입니다.

팩토리 클래스에서 유형별 구분은 메서드 네임과 파라미터 수로 구분하도록 했습니다.
이를 구현하면서 현재 템플릿의 항목을 String으로 받고 있지만 별도의 객체로 두는 것도 괜찮을 것 같다는 생각이 들었습니다.
다만 너무 늘어지는 것 같아 String 형태를 유지했습니다.

2024-02-13 10:09 UTC, Hejow approved these changes
고생하셨습니다 merge 하시고 나머지 부분은 조금씩 개선하보시죠~

2024-02-13 10:13 UTC, merged