Update(.ajaja): 응원 리마인드 알림톡 방식 적용
New-Barams/This-Year-Ajaja-BE pull request #180
Opened 2024-02-19 02:07 UTC by 2jie0516

# 🔍 어떤 PR인가요?
- 응원 리마인드에 알림톡 스케줄링 방식을 적용하였습니다.
- 계획 스케줄링 코드들을 일부 개선하였습니다.

# 😋 To Reviewer
- 기존 ncp 요청 시 템플릿 이름이 잘못 들어가는 오류가 있어서 수정하였습니다. -> 9279f12a8da9048d689c46176a315206efdf4e99
- 비동기 처리를 담당하는 메소드가 많이 중복되어서 유틸 클래스 같은 걸로 빼면 어떨지 고민입니다..
- 기존에 논의되었던 리마인드 필드를 하나 추가했습니다.
- 리마인드 전송 오류에 5회 이내는 로그만 찍고 최대 요청 횟수가 초과되면 그때 리마인드 예외 핸들러를 호출하도록 하였습니다. (최종적으로 전송을 실패했을 경우만)

# ✅ 작성한 테스트
- send_Success_WithNoException
- send_Fail_ByExternalApiFailed
- send_Success_WithNoException
- send_Fail_ByExternalApiFailed

2024-02-19 03:14 UTC, JuwoongKim reviewed
세한님 PR 재미있게 봤습니다.
리뷰보다는 프로젝트 이해를 위한 질문이 많았습니다 ㅠㅠ

비동기로 알림기능 구현, 스케줄링, 아자자의 알림 유형을 전략기법? 을 적용하신 것 같았습니다.
배울게 되게 많았네요.

스케줄링은 보통 애너테이션만 붙이면 특정 조건에 따라 별도로 동작하는 건가요??

2024-02-19 03:14 UTC, JuwoongKim commented on src/main/java/me/ajaja/infra/ses/SesSendAjajaRemindService.java
> +				return null;
반드시 handle을 사용해야하기 때문에 null을 반환하는건가요??

2024-02-19 03:14 UTC, JuwoongKim commented on src/main/java/me/ajaja/infra/ses/SesSendPlanRemindService.java
> +public class SesSendPlanRemindService extends SendRemindPort {
아자자는 SendAjajaStrategy, 계획은 SendRemindPort 로 둔 차이가 있나요??

오버라이드된 메서드상 sendTrial만 있어보이는데

2024-02-19 03:14 UTC, JuwoongKim commented on src/main/java/me/ajaja/infra/feign/ncp/model/NaverRequest.java
> +		private static final String FEEDBACK_BUTTON_NAME = "피드백 하러가기";
알림톡은 naver 인프라를 사용하는건가요???

2024-02-19 03:14 UTC, JuwoongKim commented on src/main/java/me/ajaja/infra/ses/SesSendPlanRemindService.java
> +public class SesSendPlanRemindService extends SendRemindPort {
아래 코드 봤는데 아자자가 알림톡과 메일 두개를 사용해서 그러신 걸까요??
방식은 다르지만 send로 추상화 한것 같아 보여요

2024-02-19 03:14 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/ajaja/application/model/SendAlimtalkStrategy.java
> +	private Supplier<Integer> alimtalkSupplier(NaverRequest.Alimtalk request) {
함수형 인터페이스를 따로 빼내서 메서드로 만드니 코드 보기가 훨씬 좋은 것 같습니다.
참고하도록 하겠습니다 👍👍👍

2024-02-19 03:30 UTC, kys0411 reviewed
PR 확인했습니다! 고생하셨습니다

2024-02-19 10:01 UTC, Hejow reviewed
코드 작성하시느라 고생 많으셨습니다!
코드들이 모두 약간 depth가 깊고 정확하게 동작함이 보장이 되는지 모르겠습니다.
그리고 상속을 좀 더 개선해서 사용해볼 수 있을 것 같아요! 같이 더 이야기 해보시죠

2024-02-19 10:01 UTC, Hejow commented on src/main/java/me/ajaja/global/common/TimeValue.java
> +	public boolean isBetweenOrEqual(TimeValue time) {
어떤 값 사이(between)을 표현하시려고 한다면 제 생각에 한달 이내인지 나타낼 수 있으면 좋을 것 같습니다!

2024-02-19 10:01 UTC, Hejow commented on src/main/java/me/ajaja/module/ajaja/application/model/SendAjajaStrategy.java
> +			throw new AjajaException(ErrorCode.EXTERNAL_API_FAIL);
검증과 다른 예외인 것 같아요!
외부로 보이는 노출을 가리고 싶었던 이유라면 로그를 남겨줘야할 것 같습니다!

2024-02-19 10:01 UTC, Hejow commented on src/main/java/me/ajaja/module/remind/adapter/out/persistence/model/RemindEntity.java
> +	private String endPoint;
혹시 이건 어떤 값인가요~?

2024-02-19 10:01 UTC, Hejow commented on src/main/java/me/ajaja/module/remind/application/model/RemindStrategyFactory.java
>  		return emailStrategy;
심플하게 가져가신다면 이렇게도 해볼 수 있겠군요~?!
```suggestion
		return "EMAIL".equals(remindType) ? emailStrategy : alimtalkStrategy;
```

2024-02-19 10:01 UTC, Hejow commented on src/main/java/me/ajaja/module/remind/application/port/out/SendRemindPort.java
> +		""";
`""" """`으로 작성 안하면 혹시 라인이 둘로 나뉘나용??

그리고, `FEEBACK_URL.formatted(...)`보다 `this.toFeedBackUrl(...)` 이런 형태는 어떻게 생각하시나요?
개인적으로 가지고 있는 곳에서 제공해주는게 더 좋다고 생각합니다! 그대로 사용하는 것도 나쁘지 않지만요!

2024-02-19 10:01 UTC, Hejow commented on src/main/java/me/ajaja/module/remind/domain/Remind.java
> +		return this.receiver.getType().toString();
`toString()`보다 `name()`을 선호하는 것 같아요!! 결과적으론 같지만요!

2024-02-20 03:55 UTC, 2jie0516 commented on src/main/java/me/ajaja/infra/ses/SesSendAjajaRemindService.java
> +				return null;
맞습니다!
리마인드가 성공했을 시에만 saveAjajaRemindPort.save() 메소드를 이용하여서 저장을 하고 싶은데 해당 로직을 구현하기 위해선 handle을 사용해야했습니다 ㅠ
그래서 return null을 반환하는게 좀 어색하긴 한데 구현을 위해서 그렇게 처리했습니다🥹

2024-02-20 03:58 UTC, 2jie0516 commented on src/main/java/me/ajaja/infra/ses/SesSendPlanRemindService.java
> +public class SesSendPlanRemindService extends SendRemindPort {
일단 네이밍의 차이는 아자자쪽이 헥사고날이 아니여사 Port라는 네이밍을 사용하지 않았습니다! (추후 헥사고날 전환 시 변경 예정입니다.)
그리고 send 메소드의 매개 변수 차이가 있어서 다른 구현체를 사용하였습니다!

2024-02-20 03:58 UTC, 2jie0516 commented on src/main/java/me/ajaja/infra/feign/ncp/model/NaverRequest.java
> +		private static final String FEEDBACK_BUTTON_NAME = "피드백 하러가기";
맞습니다 ㅎㅎ ncp 알림톡 서비스를 이용하고 있습니다

2024-02-20 03:59 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/ajaja/application/model/SendAlimtalkStrategy.java
> +	private Supplier<Integer> alimtalkSupplier(NaverRequest.Alimtalk request) {
👍👍

2024-02-20 04:00 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/ajaja/application/model/SendAlimtalkStrategy.java
> +	private Supplier<Integer> alimtalkSupplier(NaverRequest.Alimtalk request) {
스케줄링은 보통 애너테이션만 붙이면 특정 조건에 따라 별도로 동작하는 건가요?? -> cron 표현식으로 시간을 설정해두면 해당 시간에 알아서 동작하는 걸로 알고 있습니다!

2024-02-20 04:01 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/remind/adapter/out/persistence/model/RemindEntity.java
> +	private String endPoint;
아 이거는 슬랙에서 논의 했었던 "`카카오 리마인드인지 이메일 리마인드인지`" 를 저장해주는 필드입니다!

2024-02-20 04:02 UTC, 2jie0516 commented on src/main/java/me/ajaja/global/common/TimeValue.java
> +	public boolean isBetweenOrEqual(TimeValue time) {
사실 한달이 고정 값이어서 그렇게 표현하는게 더 좋을거 같네요 ㅠ

2024-02-20 04:02 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/ajaja/application/model/SendAjajaStrategy.java
> +			throw new AjajaException(ErrorCode.EXTERNAL_API_FAIL);
알겠습니다!

2024-02-20 04:02 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/remind/application/port/out/SendRemindPort.java
> +		""";
해당 방식도 한번 적용해보겠습니다!

2024-02-20 04:03 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/remind/domain/Remind.java
> +		return this.receiver.getType().toString();
저도 원래 name()을 주로 사용하는데 깜빡하고 toString을 썼네요 ㅋㅋ ㅠ 수정하겠습니당

2024-02-21 05:29 UTC, 2jie0516 commented on src/main/java/me/ajaja/global/common/TimeValue.java
> +	public boolean isBetweenOrEqual(TimeValue time) {
66b834d24877b2f0dfd815a1fb2b4b37718c4979 -> 이렇게 수정하였습니다!

2024-02-21 05:30 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/ajaja/application/model/SendAjajaStrategy.java
> +			throw new AjajaException(ErrorCode.EXTERNAL_API_FAIL);
5391cdb6b160d4e55af2b5554c9ad18f9132f900
최대 시도 횟수가 초과되었다는 로깅을 남기도록 하였습니다!

2024-02-21 05:31 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/remind/application/model/RemindStrategyFactory.java
>  		return emailStrategy;
말씀하신대로 적용하였습니다 ㅎ

2024-02-21 05:31 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/remind/application/port/out/SendRemindPort.java
> +		""";
b1f31b5d683ce5aa2431a83037607341ea91a90b
말씀하신 방식으로 적용하였습니다!

2024-02-21 05:31 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/remind/domain/Remind.java
> +		return this.receiver.getType().toString();
수정 완료 하였습니다!

2024-02-21 05:36 UTC, 2jie0516 commented
아좌좌 애그리거트를 좀 의미있게 만들어보고 싶어서 아좌좌 쪽 코드를 수정하였습니다! -> 86ffb442ecae98c1f0ea582f91b8c7bd65cd80b2
변경 사항은 다음과 같습니다.
1. 아좌좌 리마인드 전송 시에 필요한 값들을 추가하였습니다. (ex. 유저 정보, 타겟 정보)
2. 해당 값이 추가됨에 따라서 로직들이 일부 변경되었습니다.
3. 그에 따라 테스트 코드 또한 수정되었습니다.
@JuwoongKim @kys0411 한번 확인해보시면 좋을 것 같습니다!

@Hejow 리뷰에 남겨주신 피드백들 모두 반영하였습니다!

2024-02-21 13:02 UTC, JuwoongKim approved these changes

2024-02-21 13:02 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/ajaja/application/SchedulingAjajaRemindService.java
>  	@Scheduled(cron = WEEKLY_REMIND_TIME)
해당 애너테이션을 통해 cron? 조건에 따라 메서드가 실행되는 건가요??
별도의 사용자 요청없이요!!

2024-02-21 15:57 UTC, Hejow commented on src/main/java/me/ajaja/global/common/TimeValue.java
> +	public boolean isBetweenOrEqual(TimeValue time) {
숫자를 넣는건 괜찮은데 한달이라서 굳이 안넣어도 될 것 같기두요 ㅎㅎ?

2024-02-21 15:58 UTC, Hejow commented on src/main/java/me/ajaja/module/ajaja/application/model/SendAjajaStrategy.java
> +			throw new AjajaException(ErrorCode.EXTERNAL_API_FAIL);
이렇게 되면 로그가 두개 남게되는데 더 의미있게 개선해볼 수 있을까욤??

2024-02-21 15:58 UTC, Hejow commented on src/main/java/me/ajaja/module/remind/adapter/out/persistence/model/RemindEntity.java
> +	private String endPoint;
이렇게 되면 도메인도 맞춰서 수정해야할 것 같은데 생각해보신게 있을까요!?!?

2024-02-21 16:01 UTC, Hejow commented on src/main/java/me/ajaja/module/ajaja/application/SchedulingAjajaRemindService.java
>  	@Scheduled(cron = WEEKLY_REMIND_TIME)
내부적으로 스케쥴러가 돌아서 크론 시간에 맞춰서 자동으로 동작합니다 ㅎㅎ

2024-02-21 16:21 UTC, Hejow requested changes
PR이 조금 길어지는 것 같은데 어려운 파트다보니까 조금만 더 고생해주세요!!

이번 리뷰를 하면서 현재 infra에 과도한 코드가 몰려있다는 생각이 들었습니다.
그 결과 코드의 배치(설계)가 우리의 의도와 다르게 작동한 것 같습니다.

접근 지정자를 최대한 신경 써서 실수로라도 노출될 가능성을 줄이면 좋을 것 같습니다!
그러면 자연스럽게 헥사고날 아키텍처를 좀더 견고하게 유지할 수 있을 것 같아요.

아좌좌 쪽은 수정하신거 너무 좋았어요! 그치만 현재 PR에서 조금 벗어난 작업이었던 것 같습니다 🥹🥹

지금 추상화 수준을 더 의미있게 끌여올려보는 것도 좋을 것 같다는 생각이 들었습니다!
두 스케쥴러가 비슷한 역할을 하기 때문에 그랬던 것 같아요!

2024-02-21 16:21 UTC, Hejow commented on src/main/java/me/ajaja/module/ajaja/domain/Receiver.java
> +	}
```suggestion
	public Receiver(Long userId, String email, String phoneNumber) {
		this.userId = userId;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.validateSelf();
	}
```

2024-02-21 16:21 UTC, Hejow commented on src/main/java/me/ajaja/module/ajaja/domain/Target.java
> +	private final String title;
String은 검증하지 않아도 괜찮나요~?

2024-02-21 16:21 UTC, Hejow commented on src/main/java/me/ajaja/infra/ses/SesSendAjajaRemindService.java
> +import me.ajaja.module.remind.util.RemindExceptionHandler;
여기를 보고 생각이 많아졌습니다!
제가 놓친 부분인데 현재 설계가 잘못되서 발생한 문제입니다. 
이 코드는 여기가 아니라 ajaja 도메인 쪽에 가야할 코드네용

그리고 인터페이스를 하나 더 분리해서 지금 추상화를 한단계 더 덜어낼 수 있을 것 같단 생각이드는데 더 고민해볼까요??

2024-02-21 16:21 UTC, Hejow commented on src/main/java/me/ajaja/infra/ses/SesSendPlanRemindService.java
> +public class SesSendPlanRemindService extends SendRemindPort {
지금 봤는데 여기도 마찬가지군요!
인프라에 있을 코드가 아니라서 이동해야할 것 같아요!

2024-02-24 11:59 UTC, 2jie0516 commented on src/main/java/me/ajaja/global/common/TimeValue.java
> +	public boolean isBetweenOrEqual(TimeValue time) {
앗 그런가유 ㅋㅋ 저는 뭔가 넣는게 직관적인 것 같긴 합니다

2024-02-24 11:59 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/ajaja/application/model/SendAjajaStrategy.java
> +			throw new AjajaException(ErrorCode.EXTERNAL_API_FAIL);
2d06da0612af44fa260037cdf250f7f8ab5accc6
중복 되는 로그를 제거하고 의미있는 에러 메세지를 만들고 던지도록 하였습니다!

2024-02-24 11:59 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/remind/adapter/out/persistence/model/RemindEntity.java
> +	private String endPoint;
해당 값은 결국 유저의 리마인드 타입이라고 생각합니다! 
그래서 애그리거트에는 엔드 포인트에 해당 하는 값을 따로 추가하지는 않았습니다 😇

2024-02-24 11:59 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/ajaja/domain/Receiver.java
> +	}
추가하였습니다 ㅎㅎ

2024-02-24 11:59 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/ajaja/domain/Target.java
> +	private final String title;
해당 부분에 검증을 넣지 않은 이유는, 엔티티에는 없는 값이어서 필드에 값이 안들어가는 경우가 있기때문입니다!

2024-02-24 11:59 UTC, 2jie0516 commented on src/main/java/me/ajaja/infra/ses/SesSendAjajaRemindService.java
> +import me.ajaja.module.remind.util.RemindExceptionHandler;
e0b94ec804ed9d93b14f125ed887746db9db026f 
인프라는 전송의 역할만 수행하고 비동기 예외 처리 및 그 외 작업은 도메인에서 수행하도록 변경하였습니다 😇

2024-02-24 12:00 UTC, 2jie0516 commented on src/main/java/me/ajaja/infra/ses/SesSendPlanRemindService.java
> +public class SesSendPlanRemindService extends SendRemindPort {
d4118347204d853b4dc9d3d7b1697d8cc320ae94
위와 같은 방식으로 변경하였습니다!

2024-02-24 12:01 UTC, 2jie0516 commented on src/main/java/me/ajaja/infra/ses/SesSendAjajaRemindService.java
> +import me.ajaja.module.remind.util.RemindExceptionHandler;
e0b94ec804ed9d93b14f125ed887746db9db026f 
인프라는 전송의 역할만 수행하고 비동기 예외 처리 및 그 외 작업은 도메인에서 수행하도록 변경하였습니다 😇

2024-02-24 12:06 UTC, 2jie0516 commented
@JuwoongKim 변경된 ajaja 애그리거트에 맞게 발자취 객체 생성자 매개변수를 변경하였습니다! -> b340f84efb7a3b1c1b75d5c75c7a78338fa661b9

@Hejow 리뷰 남겨주신 내용 코멘트 남겨드렸습니다! 추상화 작업도 바로 진행해보겠습니당

2024-02-27 06:58 UTC, Hejow commented on src/main/java/me/ajaja/module/remind/adapter/out/persistence/model/RemindEntity.java
> +	private String endPoint;
근데 table 관점에서 생각해봤을 때 end_point라는 칼럼이 조금 어색해서 이름을 조금 수정해도 좋을 것 같아요!!

2024-02-28 11:38 UTC, 2jie0516 commented
추상 클래스에 공통 인터페이스를 적용하는 작업을 일부 진행해보았습니다! -> 2a5ab247c4c83d2ba8321eb57e80a3f9f3449ad8
다만 아직 인터페이스 부분이 좀 부족한 상황인데, 구현적인 문제에 좀 부딪혔습니다 ㅠ

추상 클래스에 있는 send() 메서드에서 리마인드를 전송하는 로직을 구현해보려고 하였으나 구현체(adapter)에 있는 전송 로직을 어떻게 가져올 지 고민이 많이 되었습니다.
그래서 인터페이스를 구현한 추상 클래스는 예를 들어 send(class<?> sender) 라는 메소드를 가지고 `리플렉션`을 적용해서 처리하려고 했는데 예외 처리가 급격히 늘어나서 일단 보류해놓은 상황입니다! 

아니면 혹시 제가 너무 어렵게 생각하고 있을 걸까요.. 피드백 주고 받으면서 계속 보완해보겠습니다!

2024-02-29 19:48 UTC, Hejow approved these changes
PR이 너무나도 길어져서 우선 merge하고 수정해보는 방향으로 가볼게요!

2024-02-29 19:48 UTC, Hejow commented on src/main/java/me/ajaja/module/ajaja/application/model/SendAjajaStrategy.java
> +package me.ajaja.module.ajaja.application.model;
모델에 있기에는 살짝 어색한 것 같아요! 
Model은 표현하는 객체에 가까운데 이 친구는 규격을 나타내잖아요?

2024-02-29 19:48 UTC, Hejow commented on src/main/java/me/ajaja/module/ajaja/domain/Ajaja.java
이 쪽은 제가 이번 PR의 핵심이 아닌 것 같아서 안볼게요!! 
다음에 수정할 때 집중해서 개선해보겠습니다

2024-02-29 19:48 UTC, Hejow commented on src/test/java/me/ajaja/module/ajaja/application/model/SendAlimtalkStrategyTest.java
> +		sleep(100);
제 테스트 코드에서도 sleep이 있긴한데 곧 지울 예정이라서 최대한 안 써보는 방향으로 개선해보시죠!

2024-02-29 19:48 UTC, Hejow commented on src/test/java/me/ajaja/module/ajaja/application/model/SendEmailStrategyTest.java
> +		sleep(100);
위 리뷰와 마찬가지입니당 ㅎㅎ

2024-02-29 19:48 UTC, Hejow commented on src/test/java/me/ajaja/module/remind/adapter/out/infra/SendAlimtalkAdapterTest.java
> +		sleep(100); // 비동기 메소드 처리 시간 확보
여기도 마찬가지입니당 ㅎㅎ

2024-02-29 19:56 UTC, merged