Add(.footprint) : 발자취 생성 시 태그 생성  기능 추가
New-Barams/This-Year-Ajaja-BE pull request #190
Opened 2024-03-02 12:02 UTC by JuwoongKim

# 🔍 어떤 PR인가요?
- 발자취 생성 기능에 태그도 함께 생성되는 기능을 추가했습니다. 

# 😋 To Reviewer
- 공통으로 사용하는 태그에 대해선 논의한 대로 중간 테이블을 사용했습니다.

- jpa 엔티티 패키지를 도메인에서 adapter쪽으로 이동했습니다. 

- 엔티티에서 beanValidation 검증은 추가하지 않았습니다. not null 체크만 해두었어요. 
  순수한 도메인 객체가 아닌 데이터 매핑 엔티티로써 jpa에서 제약조건을 걸어주는게 적합하다고 생각했습니다. 요부분 의견 궁금합니다. 

-  port 가 있는 만큼 활용해 봤어요. 하나의 태그 인터페이스를 두고 각 도메인마다 구현체를 만들었습니다. 의존성 주입시 @Qulifier를 사용해서 각 도메인마다 도메인에 맞는 태그 생성 서비스를 사용하도록 해봤습니다.

- 좀 더 중복을 방지 할 수 있을 것 같긴한데 너무 필요 이상으로 고민하는 것 같아 짧게 끊어 pr 날립니다.

# ✅ 작성한 테스트
- [ ] createTag_And_FootprintTag_When_Tag_NotExist
- [ ] create_Only_FootprintTag_When_Tag_Exist
- [ ] createFootPrint_Success_With_NoExceptions

 

[//]: # (# 🫡 관련 Issue )

2024-03-02 12:44 UTC, 2jie0516 reviewed
코드에 주웅님이 고민을 많이 하신게 느껴져서 저도 최대한 꼼꼼하게 보았습니다! 
작업하시느라 수고하셨습니당

2024-03-02 12:44 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/footprint/application/port/CreateFootprintService.java
> +
개행이 한번 더 들어가있는 것 같습니당

2024-03-02 12:44 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/tag/application/CreateFootprintTagService.java
> +		Set<String> nonDuplicatedTagNames = new HashSet<>(tagNames);
개인적인 생각인데 nonDuplicated 라는 것은 set를 씀으로써 충분히 전달되지 않을까유 ??

2024-03-02 12:44 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/tag/application/CreatePlanTagService.java
> +	}
이건 뭔가유?? 🥲

2024-03-02 12:44 UTC, 2jie0516 commented on src/test/java/me/ajaja/module/tag/application/CreateFootprintTagServiceTest.java
> +		when(tagRepository.findByName(anyString())).thenReturn(Optional.of(new Tag("tag")));
54번 라인에 new Tag("tag") 대신에 위에서 선언한 tag가 들어가도 되지 않나유??

2024-03-02 12:44 UTC, 2jie0516 commented on src/test/java/me/ajaja/module/tag/application/CreateFootprintTagServiceTest.java
> +	FootprintTagRepository footprintTagRepository;
아래것만 private이 안 붙어있는 이유가 있나용??

2024-03-02 13:00 UTC, kys0411 commented on src/main/java/me/ajaja/module/tag/application/port/out/CreateTagPort.java
> +	void createTags(Long targetId, List<String> tagNames);
create 라고만 해도 충분할 것 같아요!?

2024-03-02 13:01 UTC, kys0411 commented on src/main/java/me/ajaja/module/tag/application/CreatePlanTagService.java
> +	}
요거는 제가 해야되는거죠?.?

2024-03-02 13:06 UTC, kys0411 commented on src/main/java/me/ajaja/module/tag/application/CreateFootprintTagService.java
> +	}
메서드 이름이랑 내용이 뭔가..? 안맞는 느낌입니다ㅎ

2024-03-02 13:06 UTC, kys0411 commented on src/main/java/me/ajaja/module/tag/application/CreateFootprintTagService.java
> +		footprintTagRepository.save(footprintTag);
이것도 따로 뺄 수 있으면 빼는게 좋아보여용

2024-03-02 13:07 UTC, kys0411 reviewed
중님 고생많으셨습니다ㅎㅎ

2024-03-02 13:07 UTC, 2jie0516 commented on src/main/java/me/ajaja/module/tag/application/CreatePlanTagService.java
> +	}
오 그러면 todo 같은 걸로 남겨 놓는 것도 좋을거 같습니당

2024-03-03 08:59 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/application/port/CreateFootprintService.java
> +
(완)
마음이 좀 급했나봅니다!! 수정했습니다.

2024-03-03 09:05 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/tag/application/CreateFootprintTagService.java
> +		Set<String> nonDuplicatedTagNames = new HashSet<>(tagNames);
맞습니다. 저도 네이밍하면서 과하다고 생각이 들긴했습니다. ㅋㅋㅋ
우선 어떻게 느껴질지도 궁금해서 일단 적어봤네요 ㅎㅎ
수정하겠습니다!

2024-03-03 09:18 UTC, JuwoongKim commented on src/test/java/me/ajaja/module/tag/application/CreateFootprintTagServiceTest.java
> +		when(tagRepository.findByName(anyString())).thenReturn(Optional.of(new Tag("tag")));
😂😂 맞습니다!! 
반영하겠습니다.

2024-03-03 09:18 UTC, JuwoongKim commented on src/test/java/me/ajaja/module/tag/application/CreateFootprintTagServiceTest.java
> +	FootprintTagRepository footprintTagRepository;
😂😂 없습니다!!
반영했습니다.

2024-03-03 09:19 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/tag/application/port/out/CreateTagPort.java
> +	void createTags(Long targetId, List<String> tagNames);
좋슴다!!

2024-03-03 09:21 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/tag/application/CreateFootprintTagService.java
> +		footprintTagRepository.save(footprintTag);
요거하고 위에 부분하고 제가  ifPresentOrElse 에 좀 꽂힌 것 같네요.
이런 용도가 아닌것 같은데!
수정해보겠습니다.

2024-03-03 09:31 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/tag/application/CreatePlanTagService.java
> +	}
네! 그렇긴한데 이렇게 적용하는게 괜찮을지는 한번 봐야알 것 같네요
예슬님 생각은 어떠신가요??
@kys0411

2024-03-03 14:35 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/tag/application/port/out/CreateTagPort.java
> +	void createTags(Long targetId, List<String> tagNames);
피드백 반영 : 110ffe9855dd48605b95c8f206aa86a1413e0e75

반환값 메서드명 변경해서 기존 코드 변경없이 수정했습니다.

2024-03-03 14:36 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/tag/application/CreateFootprintTagService.java
> +	}
피드백 반영 : 110ffe9855dd48605b95c8f206aa86a1413e0e75

한번에 여러개를 처리하려다 보니 꼬였었네요 수정했습니다.

2024-03-03 14:39 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/tag/application/CreateFootprintTagService.java
> +		footprintTagRepository.save(footprintTag);
피드백 반영 : 110ffe9855dd48605b95c8f206aa86a1413e0e75

마찬가지로 수정했습니다. 
글고 궁금해서 save 반복문으로 하면 어떻게 되나 봤는데,
상위 트랜젝션 있으면 하나로 묵이고 쓰기 지연으로 한번에 쿼리 보내더라고요.
비록 하나씩 쿼리문을 날리지만, 태그가 5개 이하라는 점에서는 배치 모드로 따로 설정하지 않아도 괜찮을 것 같습니다. 

혹시 몰라 간단히 테스트 한거 첨부합니다.
[jpa save 반복하면??](https://www.notion.so/jpa-save-46753652e2fb4d85acd9e20336506ec2?pvs=4)

2024-03-04 04:17 UTC, Hejow requested changes
코드 작성하시느라 고생 많으셨습니다! 
이번 리뷰를 보면서 핵심적으로 본 부분은 두가지입니다.

### 헥사고날 적용
Tag 도메인 쪽에서 헥사고날을 반영하려고 하신 것 같습니다.
현재 도메인 모델과 영속성 모델을 분리하지 못했는데 아키텍처만 도입하려고 하면, 이는 도구를 다르게 사용하는 것과 동일합니다. 

헥사고날이란 **DDD를 지원하는 아키텍처이자 도메인을 지키는 아키텍처**입니다. 
현재 도메인 모델이 없는데 헥사고날만 적용하면 안되겠지요??
따라서, 돌려놓거나 도메인 모델과 영속성 모델을 분리하는 것이 좋아보입니다.

참고로 꼭 모든 모듈(패키지)에서 헥사고날을 적용하지 않아도 무방합니다! 
해야겠다는 생각이 들때 해도 괜찮습니다. (이 부분은 예슬님과 상의해서 지금 태그 쪽은 반영하지 않아도 무방하다고 판단해서 아직 반영하지 않은 것 입니다 ㅎㅎ)

### Qualifier
`Qualifier`로 빈을 구분한다는 것은 **클라이언트 쪽에서 직접적인 정보를 알고 있어야한다**는 말과 동일합니다. 

둘이 진짜 중복이 아니라 **우발적 중복**(가짜 중복)이라면 추후 변화 가능성이 있기 때문에 이름을 바꿔서 사용하는 것이 좋아보입니다.
반대로, 진짜 중복(로직은 완벽하게 동일해 보입니다)이라면 제네릭하게 사용할 수 있게해서 코드 중복을줄이는 것이 나아보입니다!

마무리하면 여러모로 많이 고민하신 것은 보이지만, 클래스가 많아지는 것에 대해서는 경계하고 있지 않? 라는 생각이 들었습니다!! 추가적인 내용은 리뷰 참고하시기 바랍니다 ㅎㅎ

2024-03-04 04:17 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/application/port/CreateFootprintService.java
> +import org.springframework.beans.factory.annotation.Qualifier;
이거 안 쓰는 방법이 더 좋을 것 같은데 어떻게 보시나요?
네이밍 수정하거나 빈 이름 명시해주거나!

2024-03-04 04:17 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/application/port/CreateFootprintService.java
> +		Long createdFootprintId = createFootprintPort.create(footprint);
네이밍이 나쁘지 않은데 너무 길어서 킹받아요!

2024-03-04 04:17 UTC, Hejow commented on src/main/java/me/ajaja/module/tag/adapter/out/persistence/FootprintTagRepository.java
> +public interface FootprintTagRepository extends JpaRepository<FootprintTag, Long> {
노출이 가능하군요?

2024-03-04 04:17 UTC, Hejow commented on src/main/java/me/ajaja/module/footprint/application/port/CreateFootprintService.java
> +import me.ajaja.module.tag.application.port.out.CreateTagPort;
이 포트는 발자취 쪽에 있고 구현을 tag 쪽에서 하는게 맞지 않을까요?

2024-03-04 04:17 UTC, Hejow commented on src/main/java/me/ajaja/module/tag/adapter/out/persistence/model/FootprintTag.java
> +public class FootprintTag {
`BaseEntity`는 상속받지 않아도 괜찮을까요?

2024-03-04 04:17 UTC, Hejow commented on src/main/java/me/ajaja/module/tag/adapter/out/persistence/model/Tag.java
> +package me.ajaja.module.tag.adapter.out.persistence.model;
지금 도메인과 분리되지도 않았는데 섵불리 헥사고날을 반영한 것 같습니다!
기존 상태로 내버려두거나 도메인 모델과 영속성 모델을 확실히 분리하고 작업을 진행하시면 좋을 것 같아요

2024-03-04 04:17 UTC, Hejow commented on src/main/java/me/ajaja/module/tag/application/port/out/CreateTagPort.java
> +	List<String> create(Long targetId, List<String> tagNames);
`List<String>`을 리턴 받는 이유가 있을까요? 사용하지 않는 것 같아요!
네이밍도 `tags`면 충분할 것 같아요!

2024-03-04 08:10 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/tag/adapter/out/persistence/model/Tag.java
> +package me.ajaja.module.tag.adapter.out.persistence.model;
맞습니다.
현재 태그 도메인에서 도메인과 엔티티를 분리할 이유가 없다는 점에서 기존 형식을 유지하도록 하겠습니다.

제가 모든 모듈(패키지)이 일관성을 가져야한다는 유연하지 못한 사고를 가지고 있었네요.
모듈은 통일된 패키지 구조를 가져야한다고 생각했었습니다. 

저도 태그쪽은 도메인과 엔티티를 분리할 필요가 없다고 생각했습니다.
아직까진 매핑 이외에는 별도의 역할이 없기 때문입니다.

그래서 동일한 패키지 구조를 가져야한다는 생각에서  태그가 persistance.model에 가까워 이동 했었어요.
이부분도 헥사고날 아키텍쳐를 패키지 구조 차원에서만 이해한 것 같기도 합니다.

2024-03-04 08:16 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/tag/application/port/out/CreateTagPort.java
> +	List<String> create(Long targetId, List<String> tagNames);
네 저도 처음에는 void로 사용했습니다.

하지만 예슬님과 통일하려다보니 반환값 부분을 고민하게 되었고, 추후 태그 수정 부분에도 사용하시는 것 같아 맞춰 두었습니다.

태그 처리에 대한 부분도 기존 논의된 방식이 있을 것이라 생각해서 기존 형식을 따르는 방향으로  작성했었습니다.
이 부분은 많이 변경될 것 같아 변경 후 다시 코멘트 적어보겠습니다.

2024-03-04 08:21 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/tag/adapter/out/persistence/model/FootprintTag.java
> +public class FootprintTag {
네! 
태그 모듈에서 해당 객체가 도메인의 역할을 가질때는 객체 자체에서 제약조건을 검증하는게 맞다고 생각합니다. 

이부분도 태그 객체를 단순히 데이터 매퍼 역할로만 본 결과였습니다. 
매퍼라면 컬럼 제약조건으로 체크하는게 더 맞다고 생각했고요! `@Colume(nulllable=false)`

2024-03-04 08:22 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/tag/adapter/out/persistence/model/FootprintTag.java
> +public class FootprintTag {
혹시 위의 코멘트 자체에 대해서는 어떻게 생각하세요? 생각이 다를 것 같다는 생각도 드네요

2024-03-04 08:23 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/tag/adapter/out/persistence/FootprintTagRepository.java
> +public interface FootprintTagRepository extends JpaRepository<FootprintTag, Long> {
어우 진짜 이런실수 한번 더하면 지옥가겠습니다!!

2024-03-04 08:24 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/application/port/CreateFootprintService.java
> +		Long createdFootprintId = createFootprintPort.create(footprint);
다른분들 피드백을 전부 고려해봤을 때 제가 좀 장황하게 네이밍을 하는 것 같네요. 
수정해보겠습니다!

2024-03-04 09:27 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/application/port/CreateFootprintService.java
> +import org.springframework.beans.factory.annotation.Qualifier;
체크

2024-03-04 09:27 UTC, JuwoongKim commented on src/main/java/me/ajaja/module/footprint/application/port/CreateFootprintService.java
> +import me.ajaja.module.tag.application.port.out.CreateTagPort;
체크

2024-03-04 10:18 UTC, Hejow approved these changes

2024-03-04 10:18 UTC, merged