[AJA-444] 보낸 리마인드 조회 코드 리팩토링 및 패키지 구조 변경
New-Barams/This-Year-Ajaja-BE pull request #83
Opened 2023-11-25 13:58 UTC by 2jie0516

# 🔍 어떤 PR인가요?
- 보낸 리마인드 조회 시에 사용하는 코드를 수정하였습니다.
- 패키지 구조를 컨벤션에 맞게 변경하였습니다.
- 시간을 통합적으로 관리하는 time vo를 추가하였습니다.

# 😋 To Reviewer
- 패키지 변경이 이루어지면서 file changed가 좀 많이 생겼습니다. ㅠ
- Mapstruct를 사용하려고 했으나 오류를 계속 해결하지 못하여 mapper를 직접 만들어서 사용하였습니다.
- 계획 , 피드백 , 리마인드 정보를 한번에 가져오려고 했으나 조인으로 인한 데이터 중복 문제가 발생하여서 지금은 각자 가져오는 식으로 하였습니다. -> 이 부분은 좀 더 개선이 필요해보입니다 !
- 시간을 구할 수 있는 vo를 추가하였습니다.

# ✅ 작성한 테스트
- [ ] findRemindInfoByPlanId_Success_WithNoException
- [ ] findNoRemindInfoByPlanId_Success_WithNoException
- [ ] findRemindInfoByPlanId_Success_WithNoException
- [ ] findNoRemindInfoByPlanId_Success_WithNoException

[//]: # (# 🫡 관련 Issue )
- mpastruct bean 초기화 오류
- join으로 인한 데이터 중복

2023-11-25 14:56 UTC, Hejow requested changes
코드 작성하시느라 수고 많으셨습니다!
남겨드린 리뷰 한번 확인 부탁드려요! 이번건 모두 답이 필요할 것 같습니다 🥹

2023-11-25 14:56 UTC, Hejow commented on src/main/java/com/newbarams/ajaja/global/common/TimeValue.java
> +public class TimeValue {
Value의 가장 큰 특징은 무엇일까요!?!?!?

2023-11-25 14:56 UTC, Hejow commented on src/main/java/com/newbarams/ajaja/module/plan/infra/PlanQueryRepository.java
> +package com.newbarams.ajaja.module.plan.infra;
이거를 아직 infra 쪽으로 냉정하게 분리하자는 이야기는 안했던 것 같은데.. 어떻게 생각하시나요 ㅠㅠ!?!?

2023-11-25 14:56 UTC, Hejow commented on src/main/java/com/newbarams/ajaja/module/remind/dto/GetRemindInfo.java
> +		}
개인적으로 이 코드는 이해하기 어려운데 제 의견은 다음과 같습니다!
1. record는 데이터임을 표현하기 위해서 만들어진 class입니다. 근데 **객체의 오버로딩을 record에 적용하는 것은 어색**하다고 생각합니다.
2. 이렇게 파라미터에 따라서 **생성되는 인스턴스의 성질이 많이 다르다면** 정적 팩토리 메서드를 사용해서 **어떤 형태로 생성 되는지 메서드 이름으로 표현**해주는 것이 옳다고 생각합니다.
3. 팀 컨벤션 상으로 DTO에 변환 로직을 사용하지 않기로 했습니다! 이거는 **생성자를 사용했다 뿐이지 생성로직과 다를 바가 없다고 생각**합니다.

2023-11-25 14:56 UTC, Hejow commented on src/main/java/com/newbarams/ajaja/module/remind/dto/GetRemindInfo.java
> +		}
다시 보니까 이 DTO 전에 제가 컨벤션이 어색하다고 말씀 드렸는데 진짜 전체적으로 어색한 것 같습니다!
다시 한번 팀 컨벤션에 맞게 수정해주실 수 있을까요~?

2023-11-25 14:56 UTC, Hejow commented on src/main/java/com/newbarams/ajaja/module/remind/dto/PlanResponse.java
어색한 부분이 많은 것 같은데 한번 의견을 들어보고 싶습니다!

2023-11-25 14:56 UTC, Hejow commented on src/main/java/com/newbarams/ajaja/module/remind/infra/RemindQueryRepository.java
> +	}
의미없이 메서드를 분리해서 오히려 코드의 복잡도를 늘렸다고 생각하는데 어떻게 보시나요?
mapper의 메서드 이름이 적절하게 부여되지 않아서 불필요하게 메서드가 추가되었다고 생각합니다.

2023-11-25 14:56 UTC, Hejow commented on src/main/java/com/newbarams/ajaja/module/remind/infra/RemindQueryRepository.java
> +	private GetRemindInfo.CommonResponse getEmptyResponse(Plan plan) {
get으로 시작하는 네이밍이 다소 어색합니다. 
get은 어디선가 가져오는 느낌인데 이 경우는 생성해주는 로직에 더 가깝다고 생각이 듭니다!

2023-11-25 14:56 UTC, Hejow commented on src/main/java/com/newbarams/ajaja/module/remind/infra/RemindQueryRepository.java
> +		int lastRemindMonth = timeValue.getMonthFrom(reminds.get(sentMessages.size() - 1).getPeriod().getStarts());
디미터의 법칙을 지키면 좋을 것 같습니다!

2023-11-25 14:56 UTC, Hejow commented on src/main/java/com/newbarams/ajaja/module/remind/infra/RemindQueryRepository.java
> +	TimeValue timeValue = new TimeValue();
또 상태를 가지고 있는 코드를 생성하셨어요..!

2023-11-25 14:56 UTC, Hejow commented on src/main/java/com/newbarams/ajaja/module/remind/mapper/RemindInfoMapper.java
> +			sentRemindResponses.add((new GetRemindInfo.SentRemindResponse(
DTO를 record로 사용해서 데이터임을 나타내긴하지만 꼭 데이터가 작은 조각의 덩어리일 필요는 없습니다!
중첩된 형태로 되어있어도 상관 없을 것 같습니다!

2023-11-25 23:07 UTC, kys0411 commented on src/main/java/com/newbarams/ajaja/module/plan/domain/Plan.java
>  	}
this가 있고 없고의 차이가 있나유?!

2023-11-25 23:14 UTC, kys0411 commented on src/main/java/com/newbarams/ajaja/module/remind/infra/RemindQueryRepository.java
> +	}
이 메서드가 어떤 일을 하나요?.? 정말 몰라서 여쭤봅니다!

2023-11-25 23:19 UTC, kys0411 commented on src/main/java/com/newbarams/ajaja/module/remind/dto/GetRemindInfo.java
> +		public FutureRemindResponse(int remindMonth, int remindDate) {
GetRemindInfo.FutureRemindResponse -> 이렇게 봤을 때 의미를 한번에 파악하기는 힘든 것 같아요 ㅜ 간결하게 줄이셔도 좋을 것 같습니다!

2023-11-25 23:21 UTC, kys0411 commented on src/main/java/com/newbarams/ajaja/module/remind/dto/GetRemindInfo.java
> +		public FutureRemindResponse(int remindMonth, int remindDate) {
개인적으로는 단어의 중복만 없애도 좋을 것 같습니다! SendRemindResponse도 그렇구요! 제 생각입니닷

2023-11-25 23:23 UTC, kys0411 commented on src/main/java/com/newbarams/ajaja/module/feedback/dto/GetAchieve.java
> +}
이 레코드는 어디서 쓰이나요?.?

2023-11-25 23:29 UTC, kys0411 commented on src/main/java/com/newbarams/ajaja/module/feedback/domain/repository/FeedbackRepositoryCustomImpl.java
>  	}
메서드 이름 오타난 건가유?.?

2023-11-25 23:33 UTC, kys0411 commented on src/main/java/com/newbarams/ajaja/module/feedback/domain/repository/FeedbackRepositoryCustomImpl.java
>  	}
혹시 isCurrentYear() 조건을 추가해준 이유가 무엇인가요?.?

2023-11-25 23:42 UTC, kys0411 commented on src/main/java/com/newbarams/ajaja/module/remind/infra/RemindQueryRepository.java
> +	public GetRemindInfo.CommonResponse findAllRemindByPlanId(Plan plan, List<Feedback> feedbacks) {
FeedbackRepo랑 네이밍 형식이 살짝 다른 것 같아요!

2023-11-26 14:11 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/global/common/TimeValue.java
> +public class TimeValue {
불변성입니다.. !!
109d4bb966f39c9ce99c857a2b9dbd312f6c2611 아까 얘기한 내용 기반으로 조금 수정해보았습니당

2023-11-26 14:11 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/plan/infra/PlanQueryRepository.java
> +package com.newbarams.ajaja.module.plan.infra;
6617908f10f4c88d4dc3198ec9dfe9d1ea1df2ee 다시 변경하였습니다 🥹

2023-11-26 14:13 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/remind/dto/GetRemindInfo.java
> +		}
2856755afd27fa56d550f1ebecbedadc4b218442 피드백 반영하였습니다 .. !

2023-11-26 14:13 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/remind/dto/PlanResponse.java
엇 해당 메소드는 사용하지 않아서 제거하였습니당

2023-11-26 14:14 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/remind/infra/RemindQueryRepository.java
> +	}
4c6ec67848b4c7f27883c3ceed8f02fbd0c2defa 피드백 반영
- 코드를 분리하고 싶어서 좀 욕심을 부린거 같습니당 ...🥹

2023-11-26 14:14 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/remind/infra/RemindQueryRepository.java
> +	private GetRemindInfo.CommonResponse getEmptyResponse(Plan plan) {
71a3cd114af232a6a99b266784050a90e7f47106 `create`로 변경하였습니다!

2023-11-26 14:15 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/remind/infra/RemindQueryRepository.java
> +		int lastRemindMonth = timeValue.getMonthFrom(reminds.get(sentMessages.size() - 1).getPeriod().getStarts());
9b3b10f372eecafffca4c03fdb3c1338a137e5ed 반영하였습니다 👍

2023-11-26 14:15 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/remind/infra/RemindQueryRepository.java
> +	TimeValue timeValue = new TimeValue();
시간vo 수정하면서 제거하였습니다 ㅠ

2023-11-26 14:16 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/remind/mapper/RemindInfoMapper.java
> +			sentRemindResponses.add((new GetRemindInfo.SentRemindResponse(
저번에 레이님이 말씀해주신 내용이군요 ... 
이건 수정하는데 시간이 좀 필요할 거 같습니다 ㅠ

2023-11-26 14:17 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/plan/domain/Plan.java
>  	}
직관성을 위해서 this를 붙이는 것을 선호합니당!

2023-11-26 14:20 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/remind/infra/RemindQueryRepository.java
> +	}
처음 보면 약간 의아할 수도 있을 것 같은데, 
리마인드 주기가 1월이면 시작은 1월부터 -> 그래야 2(1+1)월부터 시작
그게 아니라면 0월부터 -> ex) 그래서 3월부터(0+3)부터 시작
이렇게 결과가 나오도록 하였습니다!

2023-11-26 14:20 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/remind/dto/GetRemindInfo.java
> +		public FutureRemindResponse(int remindMonth, int remindDate) {
5ffee5efc4088844aecbc04c54566ae20af1bce9 커밋 피드백 반영
- 저도 dto 네이밍이 길다고 생각하긴 해서 조금 수정해보았습니다!

2023-11-26 14:21 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/feedback/dto/GetAchieve.java
> +}
개별로 목표 달성률을 조회할 때 쓰입니다!
근데 지금 기획에서는 안 쓰이는 거 같아서 곧 지울거 같아요 🥹

2023-11-26 14:22 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/feedback/domain/repository/FeedbackRepositoryCustomImpl.java
>  	}
ee0ed0f62a37152b44b385ab30b675d25f8a0d6d 커밋 피드백 반영
- 해당 조건은 지금 생각해보면 굳이 필요없을 거 같아용! 
- 오타 수정하였습니다!

2023-11-26 14:22 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/remind/infra/RemindQueryRepository.java
> +	public GetRemindInfo.CommonResponse findAllRemindByPlanId(Plan plan, List<Feedback> feedbacks) {
메소드 네이밍 말씀하시는 거죠 ??
위 커밋에서 수정하였습니다!

2023-11-26 14:32 UTC, Hejow approved these changes
시간 VO가 추가되었으니 전역적으로 관리해야할 필요가 있겠군뇨!
저번에도 말씀드렸지만 이 VO에 대해서 엔티티에서 적용하고 싶다면 converter도 있습니다!
근데 분리할 예정이라면 따로 converter가 없어도 될 것 같구용 ㅎㅎ

2023-11-26 14:32 UTC, Hejow commented on src/main/java/com/newbarams/ajaja/global/common/TimeValue.java
> +	}
get 보다는 to가 더 알맞는 네이밍 같네용 ㅎㅎ!

2023-11-26 14:32 UTC, Hejow commented on src/main/java/com/newbarams/ajaja/module/remind/mapper/RemindMapper.java
> +		List<RemindResponse.FutureResponse> futureRespons = new ArrayList<>();
futureRespons??? 오타인가용!?!?

2023-11-26 14:40 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/global/common/TimeValue.java
> +	}
8929cd69ef68cb86926b8bd0cb13d70510486e3e 네이밍 수정하였습니다!
네이밍 어렵네요 ㅎㅎ..

2023-11-26 14:41 UTC, 2jie0516 commented on src/main/java/com/newbarams/ajaja/module/remind/mapper/RemindMapper.java
> +		List<RemindResponse.FutureResponse> futureRespons = new ArrayList<>();
해당 오타도 수정하였습니다! 네이밍 바꿀때마다 자동 변환 되면서 오타가 하나씩 생기네요 ㅠ

2023-11-26 14:45 UTC, merged